name: Release CI

on:
  push:
    branches: [ release/** ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
    - uses: actions/checkout@v2
    
    - name: set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'

    - name: Prepare KeyStore
    - run: echo ${{ secrets.KEY_STORE_BASE_64 }} | base64 --d > app/KeyStore.jks

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew bundle
      
# jobs:
#   build-and-generate-apk:
#     runs-on: ubuntu-latest
#     steps:


#       - name: Creating local.properties
#         env:
#           MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
#         run: echo MAPS_API_KEY=$MAPS_API_KEY > local.properties
#       - name: Decode google-services.json
#         env:
#           FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
#         run: echo $FIREBASE_SECRET > app/google-services.json
#       - name: Build PRD debug APK
#         run: bash ./gradlew assemblePrd
#       - name: Build DEV debug APK
#         run: bash ./gradlew assembleDev
#       - name: Upload PRD debug APK
#         uses: actions/upload-artifact@v1
#         with:
#           name: app
#           path: app/build/outputs/apk/prd/debug/app-prd-debug.apk
#       - name: Upload DEV APK
#         uses: actions/upload-artifact@v1
#         with:
#           name: app
#           path: app/build/outputs/apk/dev/debug/app-dev-debug.apk
#       - name: upload PRD artifact to Firebase App Distribution
#         uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
#         with:
#           appId: ${{ secrets.FIREBASE_APP_ID }}
#           token: ${{ secrets.FIREBASE_TOKEN }}
#           groups: testers
#           file: app/build/outputs/apk/prd/debug/app-prd-debug.apk
#       - name: upload DEV artifact to Firebase App Distribution
#         uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
#         with:
#           appId: ${{ secrets.FIREBASE_DEV_APP_ID }}
#           token: ${{ secrets.FIREBASE_TOKEN }}
#           groups: testers
#           file: app/build/outputs/apk/dev/debug/app-dev-debug.apk      
