name: Release CI

on:
  push:
    branches: [ feat/** ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Prepare KeyStore
      env:
          KEYSTORE: ${{ secrets.KEY_STORE_BASE_64 }}
      run: echo $KEYSTORE | base64 --d > app/KeyStore.jks
    - name: Decode google-services.json
      env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
      run: echo $FIREBASE_SECRET > app/google-services.json
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew bundle
    - name: Upload AAB
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: app/build/outputs/bundle/release/app-release.aab
