name: Release CI

on:
  push:
    branches: [ release/** ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'
    - name: Prepare KeyStore
      run: echo ${{ secrets.KEY_STORE_BASE_64 }} | base64 --d > app/KeyStore.jks
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew bundle
